# Generated by Django 2.1.7 on 2019-03-27 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique id for Entry model', primary_key=True, serialize=False)),
                ('access_id', models.CharField(help_text='unique access_id', max_length=20, unique=True)),
                ('sequence', models.CharField(max_length=258)),
            ],
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique id for Kingdom model', primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Kingdom label', max_length=258)),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique id for Specie model', primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Specie label', max_length=258)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='kingdom',
            field=models.ForeignKey(help_text='can store a Null value, and if the recorded is deleted the Null value is stored', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Kingdom'),
        ),
        migrations.AddField(
            model_name='entry',
            name='specie',
            field=models.ForeignKey(help_text='can store a Null value, and if the recorded is deleted the Null is stored', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Specie'),
        ),
    ]
